### ISSUE TITLE
Content Group – simple: missing the card (sub pattern)

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#1515] opened 2020-02-27 16:20 UTC
## Content Group – simple: missing card (sub component): The content group - simple doesn't currently have the card (sub pattern)
-->

## Detailed description

> Describe in detail the issue you're having.

Incorrect:
<img width="845" alt="Screen Shot 2020-02-27 at 10 17 30 AM" src="https://user-images.githubusercontent.com/56400049/75462773-5e229c80-594a-11ea-8585-5cd4060a93d4.png">

Correct:
<img width="727" alt="Screen Shot 2020-02-27 at 10 20 58 AM" src="https://user-images.githubusercontent.com/56400049/75463103-eb65f100-594a-11ea-9aa0-0de38ce653fd.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Content group - simple 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Firefox

## Steps to reproduce the issue

1. View content group -simple in storybook https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupsimple--default
2. Scroll down and you will not see the card

**Comment by RobertaJHahn** [comment] 2020-02-27 22:50
@annawen1 @RaphaelAmadeu Now that the card subpattern is finished.  Can you get it to appear on the Content group - simple pattern?  Thanks.

**Comment by RaphaelAmadeu** [comment] 2020-03-02 19:10
@RobertaJHahn, @jacobottesen-dgc 

I've tested the story using the provided link and the pattern have the card, as intended.

Here's a screenshot i took

![Screen Shot 2020-03-02 at 16.09.36.png](https://images.zenhubusercontent.com/5af9cd024b5806bc2bd31a6f/e807dfc3-3c1d-410b-8f10-8dee5f567f15)

Thanks!

**Comment by ljcarot** [comment] 2020-03-02 19:17
Looks good!  Moving this to closed.

**Closed by ljcarot** 2020-03-02 19:17 UTC
Labels: bug, dev, package: patterns, severity 2, web simplification
