### ISSUE TITLE
Table of contents, sidebar scroll indicator flashes when clicking through TOC

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1691] opened 2020-03-12 21:01 UTC
## Detailed description

**Describe in detail the issue you're having.**
On desktop, the blue sidebar (scroll indicator) of an active TOC item is not responding correctly. It appears to flash and jump back and forth to items on the list, randomly.

Current:
![TOC-flashing2-QA](https://user-images.githubusercontent.com/53093550/76566412-155aff80-6483-11ea-8c72-4e0d3d9199c3.gif)

![TOC-flashing-QA](https://user-images.githubusercontent.com/53093550/76565411-e80d5200-6480-11ea-9e53-b430538a5aa5.gif)

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
Table of contents

**What did you expect to happen? What happened instead? What would you like to see changed?**
The scroll indicator should highlight the anchor link / TOC item that the user is currently viewing. 
Design specs:
- Blue line moved to the active section
- Easing: cubic-bezier(0.2, 0, 0.38, 0.9)
- Duration: 90ms

**What browser are you working in?**
Chrome, Firefox

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web Simp

## Steps to reproduce the issue

Open the [TOC pattern in Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--dynamic-items) and click on items/links or view on [Learn test page.](http://ibmdotcom-nextjs-test.mybluemix.net/learn.html)

### Additional notes

Sometimes the scroll indicator doesn't move to active link item. This is the result:
<img width="700" alt="Screen Shot 2020-03-12 at 5 04 48 PM" src="https://user-images.githubusercontent.com/53093550/76566717-b944ab00-6483-11ea-862c-c65c0d620f56.png">

**Comment by ljcarot** [comment] 2020-03-12 21:18
@larahanlon2 on Learn page it seems to be working as intended.  We know storybook behaves odd because the right side content fits all within the display area and there's no extra content below the display, so moving to next item acts a bit awkwardly.

**Comment by larahanlon2** [comment] 2020-03-12 21:33
@ljcarot it was on the Learn page that I noticed it first then I checked Storybook and saw the same issue. It's only on **click** though – not scroll. The indicator works correctly when scrolling down the page but when you click the TOC links, that's when the problem arises.

**Closed** 2020-03-19 14:26 UTC
Labels: Airtable Done, bug, dev, package: patterns, severity 3, web simplification

**Comment by ltitle** [comment] 2020-03-19 20:01
I am still seeing this issue on the test site http://ibmdotcom-nextjs-test.mybluemix.net/learn.html

When clicking on an item in the table of contents the blue bar is often lagging and jumping between sections or even never moving to the selected section 

![image](https://user-images.githubusercontent.com/57198117/77109724-dab11400-69fa-11ea-9292-29b550b12180.png)
