### ISSUE TITLE
Product Page (Masthead):- On edge browser on clicking search icon, search field doesn't open

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#3226] opened 2020-07-21 06:06 UTC
#### **Jeff would like this fix included in the v1.9.0 hot fix**

Issue Description :- On Microsoft Edge browser when user clicks on 'Search icon' , search box to enter keyword is not getting displayed. 

## Steps to reproduce the issue

1. Enter url in the browser.
2. Click on 'Search Icon'.

URL:- http://products-page-test.mybluemix.net/

OS:- Win 10
Browser:- Edge.

![Search on edge browser.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/309c4337-a7da-4785-aa1d-0f13be032869)

**Comment by asudoh** [comment] 2020-07-21 14:39
Hi our dev team discussed offline about this, and found out that we only support latest version for Edge. (Ref: https://w3.ibm.com/standards/web/browser/)

So, is it possible for you to make sure this is tested with latest Edge? Given Edge version tends to be in sync with Chrome, it'll be 83 or 84. @ariellalgilmore kindly tried with Edge 83 in BrowserStack but couldn't reproduce the problem. Thanks! CC @jeffchew

**Comment by jeffchew** [comment] 2020-07-22 16:58
Since classic edge is not in our browser scope we are closing this issue.

cc: @chetankan @Praveen-sr @caiobozato @guilhermelMoraes @ljcarot @RobertaJHahn

**Closed by jeffchew** 2020-07-22 16:58 UTC
Labels: Airtable Done, QA, bug, dev, severity 1
