### ISSUE TITLE
Carbon Theme: LightboxMediaViewer - On g90 & g100 theme, Modal is not visible due to background color. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2958] opened 2020-06-30 11:05 UTC
## Detailed description

Issue :- On g90 & g100 theme, Modal is not visible due to background color. 

## Additional information

On g10 :-

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a8b11c86-e6a3-4988-9121-650bfb2ccfdd)

**On g90 & g100 :-**

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ce5930e3-67ad-4810-8d77-2daaff28415a)

**Comment by annawen1** [comment] 2020-07-01 13:12
@jeffchew @larahanlon2 I believe on the QA call, the modal was behaving as expected?

**Comment by larahanlon2** [comment] 2020-07-01 15:15
Hey @annawen1 I think we wanted to double-check the overlay color values. According to Carbon, here are the token values per theme. Could you check these against the modal we have in Storybook, please?

**$overlay-01**
- White: Gray 100, #161616 @ 50%
- Gray 10: Gray 100, #161616 @ 50%
- Gray 90: Gray 100, #161616 @ 70%
- Gray 100: Gray 100, #161616 @ 70%

Also, it looks like the modal container has the wrong color background. In Storybook, when I choose white theme, the background of the container is gray but it should be white. When I choose gray 10, the background is white but should be gray 10.

**Storybook – white theme:**
<img width="1467" alt="Screen Shot 2020-07-01 at 11 12 41 AM" src="https://user-images.githubusercontent.com/53093550/86260939-f1374180-bb8b-11ea-98aa-888768774ae5.png">

**Storybook – gray 10 theme:**
<img width="1478" alt="Screen Shot 2020-07-01 at 11 12 46 AM" src="https://user-images.githubusercontent.com/53093550/86261012-0613d500-bb8c-11ea-843f-70699388d9d0.png">

**Comment by caiobozato** [comment] 2020-07-15 13:14
Talking with @larahanlon2 we noticed the colors for `.bx--modal-container` are compliant with the Carbon documentation. But Lara mentioned that would be good to check that with the other designers, so they will meet to discuss that. Thanks for @ariellalgilmore and @annawen1 who helped us with the investigation.

![image.png](https://images.zenhubusercontent.com/5eed1fec732800bd837801c2/ec67c28c-e0d3-4861-97be-2ab9d8ebd253)

![image.png](https://images.zenhubusercontent.com/5eed1fec732800bd837801c2/05604e65-03da-477c-aebe-b3b9fafa157f)

![image.png](https://images.zenhubusercontent.com/5eed1fec732800bd837801c2/d8af5886-f9c4-46b8-9238-c98392980cf2)

**Comment by larahanlon2** [comment] 2020-07-17 14:40
Thanks @caiobozato I asked @sethibm to take a look as soon as he has a minute.

**Comment by sethibm** [comment] 2020-07-17 22:23
Hi @larahanlon2 and @caiobozato.  Sorry for some delay getting more eyes on this.  I reviewed and found the following:

- I can  confirm what devs reviewed, that overlay background-color for .bx--modal-container is $ui-01, and that should be Gray 10 when theme is white and white when theme is Gray 10.  I can confirm as well this is reflected in the Carbon code example for Modal.  

- The visual spec for the lightbox shows the background as white, but it doesn't specify what Carbon theme this is for, and there are not other iterations showing bgrd color for different themes.

- Also confirmed the overlay color seems to right for all themes.  On inspecting, it is as Lara noted:

White: Gray 100, #161616 @ 50%
Gray 10: Gray 100, #161616 @ 50%
Gray 90: Gray 100, #161616 @ 70%
Gray 100: Gray 100, #161616 @ 70%

- However, per the original issue, that the modal background-color is hard to distinguish from the overlay color.  It's true on Storybook, but not as evident when seen in the Carbon code examples.  See below.  This may be because the Storybook examples have hardly any space around the edges and nothing behind the overlay?  To be sure, can the lightbox be shown on a test page, as it will appear for the end user for us to review?  For example, a ContentBlockMedia that has a lightbox launcher we can see over it.  

<img width="970" alt="Screen Shot 2020-07-17 at 6 20 19 PM" src="https://user-images.githubusercontent.com/58601040/87835265-a8a1a880-c85a-11ea-9267-e14d571e3e4c.png">

<img width="914" alt="Screen Shot 2020-07-17 at 6 20 30 PM" src="https://user-images.githubusercontent.com/58601040/87835269-a9d2d580-c85a-11ea-8407-c7c27ca8edc9.png">

**Comment by larahanlon2** [comment] 2020-07-30 17:27
@sethibm and I both reviewed this from the design side. In addition to the comments above, here are some closing suggestions/concerns:

**Seth**
> It's much easier to look at the Gray 90 or Gray 100 on Carbon example, and see the opacity of the modal background in relation to the background of the modal, but in Storybook, there's no content behind the lightbox modal, or space above and below, so it's hard to test and view the original issue.

> So I suggested making a sample web page with an image that triggers the lightbox, using the darker carbon theme, so we can see how it works in a real situation, to confirm or deny this issue.

> One of the problems here was brought up before when lightbox was designed, that the semi-transparent bgrd layer that helps dim content behind the modal is so small. It looks like it's 16px. So it's hard to differentiate between the modal bgrd and the bgrd dimming color, and there is no visual context like the Carbon modal where one can see some of the content underneath (ie the rest of the web page).

> I'm also not sure this will do much to solve the actual issue.  It would just allow us to see if there's any change when users can see a bit of content in the 16px frame around edges of the lightbox.  If the padding was 32px or 64px, it would likely make a bigger difference.

**Lara:**
>I totally understand your suggestion and I do think it would be helpful, in general, to have a test page or sandbox where we could test components with actual page content so it's more realistic but I'm not sure we need that for this particular issue. I think you're probably right, that greater padding is what would make a difference to actually seeing or noticing the overlay but after looking at Wonil's designs again it's clearly intentional to have a 16px overlay background. I think it's because this tight border allows the content in the lightbox to be prominent and almost full screen...an "expressive" moment.

> My thought is that we leave the design as-is, that is, let's not create anything additional or make any modifications but we can document this concern/idea on the issue above. If adopters feel that the 16px overlay is not working then we can always encourage them to open a feature request down the line.

**Conclusion:**
If we can confirm that the original issue is resolved and that the component is using the theme tokens correctly then I say this is done.

FYI @caiobozato

**Closed** 2020-07-31 17:02 UTC
Labels: Airtable Done, QA, bug, dev, severity 4
