### ISSUE TITLE
Content Group Simple renders item title too high above optional image

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1890] opened 2020-03-27 18:20 UTC
Using v1.5.1-rc.1, When a Content Group Simple  item is configured with an image.  There is too much margin between the Simple item heading and the Simple item image.  This does not match the visual design for Learn Page. 

Please see below.
<img width="1300" alt="Screen Shot 2020-03-27 at 2 06 42 PM" src="https://user-images.githubusercontent.com/55464272/77787505-0739e100-7036-11ea-8089-bd47b1fddaec.png">

#### Additional Information
- Within the Content group - simple, there is a collection of items.  When the Content item - with image is included, the spacing between the heading and the image should be 16 and not 32.

**Comment by RobertaJHahn** [comment] 2020-04-01 15:17
Jacob will confirm whether our Content Group Simple spec and storybook are the same.  If they are then ask Ke what designs he is looking at.

**Comment by jacobottesen-dgc** [comment] 2020-04-01 16:09
I reached out to Ke for clarification because this screenshot doesn't match Content Group Simple. Waiting to hear back from Ke.

**Comment by jacobottesen-dgc** [comment] 2020-04-01 18:51
@kexuibm I looks like the content group simple has the correct spacing (32px or 2 rem) based on the sketch file:
https://ibm.box.com/s/rkkj4n9tmpiq3np9ng41dszf2y3cr4du

![Screen Shot 2020-04-01 at 1.47.44 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/2c6ce8e1-1d83-4737-aabd-a6cdc46dbd2e)

**Comment by ljcarot** [comment] 2020-04-01 19:47
Closing issue as it's working per design spec.

**Comment by RobertaJHahn** [comment] 2020-04-01 21:02
Per defect review meeting:  This defect should be reopened.  The spacing between the content group item title and the content group item image.  This scenario is not included in the Functional specs.  This fix is needed for the MVP.  The MVP delivery need date is Friday, April 3.

**Comment by ljcarot** [comment] 2020-04-01 23:05
@RobertaJHahn or @kexuibm could you clarify...this scenario is not included in the Functional specs?

**Comment by RobertaJHahn** [comment] 2020-04-02 12:15
@kexuibm You would explain better than I could.  Could post your explanation of why this scenario is not included in the functional specs to this issue.  Thanks.

**Comment by RobertaJHahn** [comment] 2020-04-02 14:47
Meeting with Ke:  Wonil confirmed with Lila that Drupal can continue with the MVP with this bug in place.

DDS:  Added to the April release.

**Comment by RobertaJHahn** [comment] 2020-04-08 15:03
design & dev review meeting notes:  
The content item has an optional image with the spacing between the heading and image.  This spacing is incorrect at 32 px.  Lila's designs include a spacing of 16 px.  The padding should be fixed in the content item between the heading and the image.

**Closed** 2020-04-16 19:55 UTC
Labels: Airtable Done, Sprint Must Have, adopter support, bug, dev, drupal
