### ISSUE TITLE
Component: Locale Modal & Footer - Search bar does not stick on to top of the Modal

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3846] opened 2020-09-02 13:32 UTC
## Detailed description

Issue: On Locale modal & Footer - Search bar does not stick on to top of the Modal, it scroll through the Country/Languages.

Note: This is happening only on Staging (https://ibmdotcom-react-staging.mybluemix.net/). On canary its working as expected.

## Additional information

![LocaleModal.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f1b0b658-fc16-4fd5-88f6-942389cf449f)

**Comment by kennylam** [comment] 2020-09-02 15:18
@Praveen-sr I can't reproduce this in any of our environments.

cc: @jeffchew @RobertaJHahn

**Comment by kennylam** [comment] 2020-09-03 13:28
@Praveen-sr @RobertaJHahn @jeffchew  Just tested in Windows Chrome/FF and Mac Chrome/FF/Safari and still cannot reproduce. Closing for now.

**Closed by kennylam** 2020-09-03 13:28 UTC
Labels: Airtable Done, bug, dev, package: react, severity 4
