### ISSUE TITLE
Error page redesign: cup cake design study

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#174] opened 2019-10-08 00:42 UTC
### User story
As a user of IBM.com, I need to know when an http error has occurred, and what to do next in order to continue with my journey.

### Notes
- This story is to redesign the existing http error page template to IDL and Carbon specs.

### Acceptance criteria
- [ ] design directions have been explored
- [ ] final design direction has been identified

### Current design
![screencapture-ibm-lksdjf-2019-10-07-20_43_21](https://user-images.githubusercontent.com/30183447/66359222-3c495e80-e944-11e9-917d-35ebd252e778.png)

**Comment by wonilsuhibm** [comment] 2019-10-08 00:46
Design ideas:

![Artboard Copy 28](https://user-images.githubusercontent.com/30183447/66359047-79f9b780-e943-11e9-9abd-6e92bcb247a2.png)

---

![Artboard Copy 25](https://user-images.githubusercontent.com/30183447/66359048-79f9b780-e943-11e9-8e3f-eb918d30fe45.png)

---

![Artboard Copy 23](https://user-images.githubusercontent.com/30183447/66359049-79f9b780-e943-11e9-88a8-5872a23e5dd0.png)

---

![Artboard Copy 22](https://user-images.githubusercontent.com/30183447/66359050-79f9b780-e943-11e9-8360-fc0954758e84.png)

**Comment by wonilsuhibm** [comment] 2019-10-08 00:46
A minimal design idea:
![Artboard Copy 34](https://user-images.githubusercontent.com/30183447/66359070-90a00e80-e943-11e9-8da5-a9af874b7029.png)

**Comment by ljcarot** [comment] 2019-10-08 12:16
I like the minimal design.

**Comment by RobertaJHahn** [comment] 2019-10-21 18:23
Duplicate of [issue 349](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/349)  Closing

**Closed by RobertaJHahn** 2019-10-21 18:23 UTC
Labels: Feature request, design, design: research, design: visual, priority: low
