### ISSUE TITLE
Vis specs: content block - simple

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1522] opened 2020-02-27 19:16 UTC
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes from the epic
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box - [ ] Design specs are available in PDF format in [this Box fodler](https://ibm.box.com/s/7f8mb1xyqdu5pimx9k1xtpl7oqrme0qf)

**Comment by RobertaJHahn** [comment] 2020-03-09 14:33
Duplicate of issue (#1509).  Closing

**Closed by RobertaJHahn** 2020-03-09 14:33 UTC
Labels: Design specs, design
