### ISSUE TITLE
Add copy line 2 to quote's source

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2685] opened 2020-06-08 13:43 UTC
### The problem
When the quote block pattern was originally designed the design intent was its source would have a third line for like a company name. I assumed this would be handled as a string with markdown or the such, if not just wrapped around.

### The solution
Add a new prop to the quote block pattern that allows for an optional 3rd line identical to the 2nd line. (See design specs for specifics there)

<img src="https://user-images.githubusercontent.com/3793636/83266572-a1c6b580-a188-11ea-9300-731ed4240d30.png" width="200px" />

### Additional information
 - [Design specs](https://ibm.box.com/s/nmf0ie8mzcim304s68fgqkz1knao1b74)
 - [Functional specs](https://ibm.box.com/s/wcjfuhhzfr3ef219bjvhhezic767rzn7)
 - [Storybook](http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-quote--default)
- **See the Epic for the Design and Functional specs information**
- Prod QA testing issue (#2705 )

#### Acceptance criteria
- [ ] Include README for the react pattern and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished
- [ ] The Canary URL is added to the Prod QA issue for their testing

**Comment by oliviaflory** [comment] 2020-06-08 14:31
Is this the same / duplicate of issue #2605 ?

**Comment by RobertaJHahn** [comment] 2020-06-22 14:40
This work is done and ready to be tested.

**Closed** 2020-06-22 14:55 UTC
Labels: Airtable Done, Feature request, dev, priority: medium
