### ISSUE TITLE
Leadspace gets overlayed on top of masthead.

### ISSUE THREAD

**Issue by ACAVJW4H** [carbon-design-system/ibm-dotcom-library#2821] opened 2020-06-18 08:51 UTC
## Detailed description

> Describe in detail the issue you're having.
I attached a screenshot

> Is this issue related to a specific component?
Yes Leadspace

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I cannot resolve Leadspace getting overlayed on top of the masthead,

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
1.8 rc-3 React/create-react-app. I kept a 1.2 version of the library where I don't see this behavior.

## Steps to reproduce the issue

1. clone repo && cd create-react app
2. yarn add relevant packages
3. Add a `<Leadspace>` component to content.js
4. yarn start

## Additional information

![Screen Shot 2020-06-18 at 11 39 14 AM](https://user-images.githubusercontent.com/2772104/84998876-158d2a00-b159-11ea-937a-aa5865ef5d6e.png)

![Screen Shot 2020-06-18 at 11 48 58 AM](https://user-images.githubusercontent.com/2772104/84999356-b67be500-b159-11ea-9ad4-7c438341bcad.png)

**Comment by RobertaJHahn** [comment] 2020-06-19 19:03
@kennylam I saw that this is not a bug in the Slack message.  Could you add a comment to this issue with your conclusions before I close it.  Thanks.

**Comment by ACAVJW4H** [comment] 2020-06-19 21:33
I might be using the component wrong, in that case, I am really sorry to bother you guys. I would really appreciate if you could point me to a sample to learn how the leadspace component works. 

I am also curious about using the component without padding, similar to the current ibm.com site. I tried setting to 0rm for edge to edge images which messes with the Text padding too. Currently a whitespace on the left and right is displayed at wider resolutions.

**Closed** 2020-06-22 12:51 UTC
Labels: Airtable Done, Not a bug, dev, severity 1
