### ISSUE TITLE
Component: Micro Footer - Border of the Search field

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3814] opened 2020-09-01 06:09 UTC
## Detailed description

Issue:  All sides of borders on the search field is not meeting the success contrast ratio
Foreground:#F4F4F4
Background:#FFFFFF

The contrast ratio is: 1.1:1

Expected :
Provide below contrast ratio.
Foreground:#8A8A8A
Background:#FFFFFF

The contrast ratio is:3.5:1
Text passed at Level AA

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ce59ffaf-c820-4205-b9eb-099e8f7cf1cc)

**Comment by kennylam** [comment] 2020-09-22 16:20
@Praveen-sr Where are you seeing this? The micro footer language-only search input looks like this
![image](https://user-images.githubusercontent.com/909118/93909639-f230c880-fccd-11ea-917e-98103f1521f9.png)

**Comment by kennylam** [comment] 2020-09-23 13:23
Duplicate of https://github.com/carbon-design-system/ibm-dotcom-library/issues/3445

**Closed by kennylam** 2020-09-23 13:23 UTC
Labels: Airtable Done, accessibilty, bug, dev, package: react, severity 2
