### ISSUE TITLE
CardGroup property requirements

### ISSUE THREAD

**Issue by ellenchoi1** [carbon-design-system/ibm-dotcom-library#2440] opened 2020-05-19 13:09 UTC
## Detailed description

> 

- The optional copy property is missing for image card is used
- Eyebrow and heading properties for image card should be optional, not required 
- Copy and heading properties for simple card should be optional, not required

These are bugs in terms of the requirements set in v1.0 of Cards Group sub-pattern functional specs: https://ibm.box.com/s/kgz9kay1nox5mjumhpzr0ygfz7tx1vww

Observed in stage: https://ibmdotcom-react-staging.mybluemix.net/

**Comment by ljcarot** [comment] 2020-05-19 13:25
@ellenchoi1 Can you provide link to where you were testing? Staging? thx

**Comment by ellenchoi1** [comment] 2020-05-19 13:36
@ljcarot  Whoops, sorry about that! Yes, stage. Added info to the ticket description too.

**Comment by RaphaelAmadeu** [comment] 2020-05-20 14:58
The heading, copy and eyebrow are not set to required in the code. 
Could you please point where you're facing this issue or provide a screenshot?
Thanks!
cc: @ellenchoi1 , @ljcarot

**Comment by ellenchoi1** [comment] 2020-05-20 15:06
Maybe it's just a typo in the readme in storybook then? See screenshot of the readme section with the property data.
<img width="960" alt="cardgroup storybook" src="https://user-images.githubusercontent.com/64159006/82462709-ea47ea00-9a89-11ea-8663-2c13c5912d86.png">

**Comment by kennylam** [comment] 2020-05-20 15:57
@ellenchoi1 `heading` is required for card otherwise it would be blank. @RaphaelAmadeu I think the confusion is that it's being labeled as `title (required)` on the Storybook knob, but the actual prop is `heading`.

**Comment by RobertaJHahn** [comment] 2020-07-06 18:50
Closing.  duplicate of issue (#2949)

**Closed by RobertaJHahn** 2020-07-06 18:50 UTC
Labels: Airtable Done, bug, dev, severity 4
