### ISSUE TITLE
Component: Card & CardLink - Card is not stretched to full screen on Mobile 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2627] opened 2020-06-02 07:41 UTC
## Detailed description

Issue :- Its a Storybook issue - Card & CardLink - Card is not stretched to full screen on Mobile as per the specs.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/22367ee6-8740-4f2d-9b9c-b52f31dad572)

**Comment by annawen1** [comment] 2020-06-25 12:54
@guilhermelMoraes didn't you already work on this?

**Comment by guilhermelMoraes** [comment] 2020-06-25 13:29
@annawen1 yeah, this may be a duplicate of the #2609. It looks just fine right now: 
![Captura de Tela 2020-06-25 às 10 24 10](https://user-images.githubusercontent.com/42848561/85728955-c3a35180-b6ce-11ea-8e04-5d97e7b67c44.png)

**Closed** 2020-06-29 19:00 UTC
Labels: Airtable Done, QA, bug, severity 4
