### ISSUE TITLE
Leaving IBM

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#754] opened 2019-12-01 22:19 UTC
### User story
As an IBM.com user, I need to be notified when I'm leaving IBM.com domain so that I can understand the new context.

### Notes
- [v18 documentation](https://northstarexamples.mybluemix.net/v18/elements/leavingibm/)

![Screen Shot 2019-12-01 at 5.19.00 PM.png](https://images.zenhubusercontent.com/5ad8a7dd4b5806bc2bcfcb61/bedb7088-3f4a-406f-9ead-095ace8a0bd2)

**Comment by RobertaJHahn** [comment] 2020-10-07 21:50
This is a duplicate of issue (#3324).  Closing.  The work will be managed under the previously mentioned issue.

**Closed by RobertaJHahn** 2020-10-07 21:50 UTC
Labels: design, epic
