### ISSUE TITLE
HTTP Error page redesign

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#175] opened 2019-10-08 00:42 UTC
As we adopt IDL on ibm.com, we need to redesign the http error pages.

### Examples:
https://www.ibm.com/common/errorpages/300.html
https://www.ibm.com/common/errorpages/303.html
https://www.ibm.com/common/errorpages/305.html
https://www.ibm.com/common/errorpages/307.html
https://www.ibm.com/common/errorpages/400.html
https://www.ibm.com/common/errorpages/401.html
https://www.ibm.com/common/errorpages/402.html
https://www.ibm.com/common/errorpages/403.html
https://www.ibm.com/common/errorpages/404.html
https://www.ibm.com/common/errorpages/405.html
https://www.ibm.com/common/errorpages/406.html
https://www.ibm.com/common/errorpages/407.html
https://www.ibm.com/common/errorpages/408.html
https://www.ibm.com/common/errorpages/409.html
https://www.ibm.com/common/errorpages/410.html
https://www.ibm.com/common/errorpages/411.html
https://www.ibm.com/common/errorpages/412.html
https://www.ibm.com/common/errorpages/413.html
https://www.ibm.com/common/errorpages/414.html
https://www.ibm.com/common/errorpages/415.html
https://www.ibm.com/common/errorpages/416.html
https://www.ibm.com/common/errorpages/417.html
https://www.ibm.com/common/errorpages/500.html
https://www.ibm.com/common/errorpages/501.html
https://www.ibm.com/common/errorpages/502.html
https://www.ibm.com/common/errorpages/503.html
https://www.ibm.com/common/errorpages/504.html
https://www.ibm.com/common/errorpages/505.html

**Comment by RobertaJHahn** [comment] 2019-10-21 18:25
duplicate of [issue 190](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/190)  Closing

**Closed by RobertaJHahn** 2019-10-21 18:25 UTC
Labels: epic, website: cupcake
