### ISSUE TITLE
Pattern: Content Block Segmented - When user changes CTA style to 'text' on knobs, card section is not displayed. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#1563] opened 2020-03-03 08:50 UTC
## Detailed description
Browsers - Firefox, Chrome & Safari

Issue :- User changes CTA style option from 'card' to 'text' from knobs, then the whole card section is hidden. Only the arrow link is seen.

## Steps to reproduce the issue

1. Open the storybook and load Content block segmented
2. Go to knobs, CTA style and change "card" to "text" option
3. Verify the card section at the last of the pattern

## Additional information

CTA style = card
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dde40445-3b30-4f71-97c3-9ba1efd00fb7)

CTA style = text
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ca83fd4b-ef8f-47c8-836e-e8e7e4a62f7d)

**Comment by kennylam** [comment] 2020-03-06 15:29
@Praveen-sr I can't reproduce this. Toggling the knobs for both CTA `type` and `style` behave as expected.

http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentblocksegmented--default

**Comment by ljcarot** [comment] 2020-03-06 17:15
I can't reproduce either @Praveen-sr .  When I change to text, I see the text
<img width="983" alt="ReTest of issue 1563" src="https://user-images.githubusercontent.com/23237857/76106029-0f0ce500-5fa4-11ea-9b68-5d4f267d9b00.png">

**Comment by photodow** [comment] 2020-03-06 17:36
@ljcarot I think this got fixed in #1556

**Comment by ljcarot** [comment] 2020-03-06 17:44
ok, so I'll close. Thx!

**Closed by ljcarot** 2020-03-06 17:44 UTC
Labels: Airtable Done, QA, bug, severity 3
