### ISSUE TITLE
Content Block Patterns have the same data-autoid value

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#1487] opened 2020-02-26 18:57 UTC
In v1.4.0, for the following Content Block patterns:

- ContentBlockSimple
- ContentBlockSegmented
- ContentBlockMedia
- ContentBlockMixed

The outermost div of the pattern have the same data-autoid attribute values (e.g dds--content-block).  This would break pattern level analytics tracking to my understanding as well as make ingestion into Drupal much more difficult. 

Instead the outermost div should have a unique pattern specific data-autoid attribute value (e.g dds--complex-narrative) for each of the above patterns.

**Comment by kennylam** [comment] 2020-02-26 19:09
Duplicate of #1490

**Closed by kennylam** 2020-02-26 19:09 UTC
