### ISSUE TITLE
Feature-card-block-large block pattern is not styled correctly when in Layout

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/ibm-dotcom-library#2649] opened 2020-06-03 20:29 UTC
Using Release 1.7.0 The Feature-card-block-large block pattern looks incorrect when rendered in the Layout Component via the following:

  <Layout nested={true} type="2-1" border={true}>
  <div>
    <FeatureCardBlockLarge
    eyebrow={eyebrow}
    heading={heading}
    copy={copy}
    cta={cta}
    image={image}
    />
    </div>
    <div></div>
   </Layout>

This layout produces the following: (note that the styling is off)
<img width="841" alt="Screen Shot 2020-06-03 at 9 53 01 AM" src="https://user-images.githubusercontent.com/55464272/83685738-21a0b580-a5b7-11ea-98fd-44603bc08b6f.png">

However if I used the following grid copied from Story book it renders correctly.

<div className="bx--grid">
  <div className="bx--row">
  <div className="bx--col-sm-4 bx--col-lg-12 bx--offset-lg-2">
      <FeatureCardBlockLarge
    eyebrow={eyebrow}
    heading={heading}
    copy={copy}
    cta={cta}
    image={image}
    />
  </div>
  </div>
  </div>

<img width="801" alt="Screen Shot 2020-06-03 at 9 53 53 AM" src="https://user-images.githubusercontent.com/55464272/83685813-3ed58400-a5b7-11ea-81d3-3a21d4c7e369.png">

**Comment by RobertaJHahn** [comment] 2020-06-04 14:42
@RaphaelAmadeu Could you take a look at this with the work you are doing with the DDS patterns issue?

**Comment by RaphaelAmadeu** [comment] 2020-06-05 18:36
@kexuibm 
Could you please share how are you implementing it inside `Layout`?

**Comment by kexuibm** [comment] 2020-06-08 13:50
> @kexuibm
> Could you please share how are you implementing it inside `Layout`?

Hi Carlos sure thing, so here is the layout where it is breaking:

<img width="416" alt="Screen Shot 2020-06-08 at 9 50 25 AM" src="https://user-images.githubusercontent.com/55464272/84038121-810f1480-a96d-11ea-8c17-dab8cf74ec43.png">

**Comment by RaphaelAmadeu** [comment] 2020-06-09 13:48
@kexuibm
Can you share some more info about this?
Like the used resolution?

I've setup this codesandbox for testing the component and the bug is not happening
https://codesandbox.io/s/tender-sunset-ou5vf?file=/src/index.js

**Comment by annawen1** [comment] 2020-06-12 00:15
Hey @kexuibm, I wonder if the `FeatureCardBlockLarge` should be placed in the `Layout` wrapper in the first place? From the [visual specs](https://ibm.ent.box.com/file/652669833356) I've seen, I believe the design intention is for the this pattern to take up 12 out of the 16 columns in desktop

**Comment by ltitle** [comment] 2020-06-12 14:32
@annawen1 You are correct. Feature card block large should take up 12 of the total 16 columns. I am guessing there may be some confusion between Feature card block large and Feature card block medium?

### **Feature card block large (as seen in Solution template design):**

![image](https://user-images.githubusercontent.com/57198117/84513687-cdbd5d00-ac97-11ea-88c2-388dffa8afcb.png)

### **Feature card block medium (as seen in Learn template design):**

![image](https://user-images.githubusercontent.com/57198117/84513742-e299f080-ac97-11ea-97f3-9abf7df68d78.png)

**Comment by RobertaJHahn** [comment] 2020-06-12 16:54
Based on the response from Lila above, this is not a bug.  Closing

**Closed by RobertaJHahn** 2020-06-12 16:54 UTC
Labels: Airtable Done, Not a bug, adopter support, adopter: drupal
