### ISSUE TITLE
Footer: Legal text link color issue 

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#2341] opened 2020-05-11 20:48 UTC
## The 'Cookie preferences' link in the legal section of the footer has the wrong link color

![Screen Shot 2020-05-11 at 3.43.54 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/c9fd142b-1a0f-4bea-a012-0afe6b18a08f)

> Currently the 'Cookie preferences' link in a dark blue but the color should be $text-02 w/ hover state of: color: $text-01
text decoration: underline

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Footer

> What browser are you working in?
Google Chrome

## Steps to reproduce the issue

1. View footer in storybook https://ibmdotcom-react.mybluemix.net/?path=/story/components-footer--default
2. View 'Cookie preferences' link in the legal section

**Comment by RobertaJHahn** [comment] 2020-05-13 17:52
closing as this is a duplicate of issue (#2305)

**Closed by RobertaJHahn** 2020-05-13 17:52 UTC
Labels: bug, dup
