### ISSUE TITLE
Content Media Block (Example Pattern) shouldn't have Image caption as per visual design and DDS spec

### ISSUE THREAD

**Issue by sridharmula** [carbon-design-system/ibm-dotcom-library#1887] opened 2020-03-27 14:22 UTC
## Detailed description

Content Block Media (Example Pattern) shouldn't have image caption and we from drupal side generating the html it's having the html. DDS spec doesn't have it and Visual design doesn't have it.
https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--default
https://ibm.ent.box.com/file/607045243803

> Is this a feature request (new component, new icon), a bug, or a general
Bug

> Is this issue related to a specific component?Content Media Block

> What did you expect to happen? What happened instead? What would you like to
> see changed? No Image Caption

> What browser are you working in?Chrome, FF

> What version of the IBM.com Library are you using?1.5.1-rc.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment] 2020-03-27 17:45
Wonil will check with Jill to see what the design intent is.  

The Functional specs do not include a restriction on the caption.
https://ibm.ent.box.com/file/607045243803

**Comment by wonilsuhibm** [comment] 2020-03-28 01:52
Per conversation with Jill, this pattern itself needs to be able to handle both as it's used without caption on the learn page template while it's used with caption on the solution page template. I believe this pattern is behaving as expected, and the showing and hiding of the caption should be determined by the template that uses this pattern.

**Comment by RobertaJHahn** [comment] 2020-03-30 19:00
Closing this issue based on Wonil's comments above.

**Comment by sridharmula** [comment] 2020-03-30 19:52
@wonilsuhibm @RobertaJHahn we don't have an option to switch on or off caption in the Content Media block.

**Comment by RobertaJHahn** [comment] 2020-04-01 20:47
During the defect review meeting, the Learn page design does not include the caption.  There is no ability provided to suppress the caption.  This defect should be reviewed by the DDS squad and reopened.

**Comment by jeffchew** [comment] 2020-04-01 22:30
@sridharmula I created a draft PR with a deploy preview here:
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1948/index.html?path=/story/patterns-blocks-contentblockmedia--default

This exposes the `Simple group media (image)` as a knob. If you remove `heading`, this removes the caption. From a React component perspective, we already have the ability to remove the caption as it is an optional field and there is no code updates required on the IBM.com Library side.

We will probably merge in this PR https://github.com/carbon-design-system/ibm-dotcom-library/pull/1948 so that the main Storybook can include this new knob as a reference.

cc: @RobertaJHahn @ljcarot @wonilsuhibm

**Comment by ljcarot** [comment] 2020-04-01 22:55
So when will PR 1948 be merged so we can give Ke and Sridhar a date.

**Comment by jeffchew** [comment] 2020-04-01 22:57
> So when will PR 1948 be merged so we can give Ke and Sridhar a date.

We can merge the PR whenever anyone approves it, it isn't part of any release though and storybook should get updated automatically.

**Comment by RobertaJHahn** [comment] 2020-04-02 14:36
Meeting with Ke:  The issue is resolved from a Drupal perspective by removing the heading as suggested by Jeff above.    Closing this issue.

**Closed by RobertaJHahn** 2020-04-02 14:36 UTC
Labels: Not a bug, drupal
