### ISSUE TITLE
Component - Local Modal - Select region it is always showing United states - English, but actual country selected is different.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2126] opened 2020-04-20 14:52 UTC
## Detailed description
Device:- Windows, Mac and Mobile
Browsers :- Chrome, Firefox and Safari 

Issue:- 
Local Modal - Actual country selected is different but on select region its always showing United states - English.

## Additional information
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/cbbbf960-77c9-41be-9b65-4e703398d5ef)

**Comment by jeffchew** [comment] 2020-04-20 15:48
This appears to be environment related, as the NodeJS deployment works fine. Going to set this as a `severity 3`, but this doesn't need to be hotfixed.

cc: @annawen1 , as you are going to be looking at issue #2047 and this would need to be addressed in there too.

![Screen Shot 2020-04-20 at 11 44 44 AM](https://user-images.githubusercontent.com/1641214/79771382-b5b30800-82fc-11ea-9564-a4f4c2fe57e4.png)

**Comment by jeffchew** [comment] 2020-04-20 20:42
This appears to now be working on latest test and staging environments for me, though I didn't really do anything... @Praveen-sr @chetankan can you let me know if you're seeing the same thing?

**Comment by Praveen-sr** [comment] 2020-04-21 07:31
@jeffchew Re checked this on [staging](https://ibmdotcom-nextjs-staging.mybluemix.net/), the country on select region is same as user selected - working fine.
Now while we select "China", we getting "An unexpected error has occurred." message and content of the page is not displayed.
![image](https://user-images.githubusercontent.com/60002341/79838041-09daec80-83d0-11ea-9b3f-042d82d1bb40.png)

**Comment by jeffchew** [comment] 2020-04-21 12:39
thanks @Praveen-sr @chetankan , should we track this down as a separate issue or maybe a new one?

@kennylam do you think it's something with the translation file for China that's causing this?

**Comment by ljcarot** [comment] 2020-04-21 12:58
I could not reproduce.  @jeffchew can you see same error?

**Comment by Praveen-sr** [comment] 2020-04-21 13:24
Steps to reproduce error message for China:-
1. Go to locale selector and select "China"
2. Page refreshes and loads Chinese page
3. Go to locale selector and and try to select any other region
4. We get the "An unexpected error has occurred." message

**Comment by jeffchew** [comment] 2020-04-21 13:26
@ljcarot I was able to replicate with the steps that @Praveen-sr outlined.

**Comment by kennylam** [comment] 2020-04-21 13:32
@jeffchew Yep it's because of the Chinese translation file. Fixing now

**Closed** 2020-04-24 13:36 UTC
Labels: Airtable Done, QA, bug, dev, severity 3
