### ISSUE TITLE
Leadspace-centered (no image and with image) - Title font weight - Carbon fix needed

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/ibm-dotcom-library#1188] opened 2020-01-24 18:47 UTC
Seen on Chrome

### **Font weight for the title in the leadspace looks thicker than designed.** 
Leadspace title should be using Expressive-Heading-05 which uses light weight for Med, Large, XL, and Max sizes. Expressive-Heading-05 only uses regular weight for the Small breakpoint.

As seen in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73095159-fc38c800-3eaf-11ea-8ede-e39545da8518.png)

Expected:
![image](https://user-images.githubusercontent.com/57198117/73095210-11adf200-3eb0-11ea-8c5a-1098edace1c0.png)

### **Font size for the description in the leadspace is not correct.**
Leadspace description should be using Expressive-Heading-03 which is 20px for Small, Med, Large and XL breakpoints and only gets larger for the Max breakpoint. You can see how the implemented sizes are not consistent.

Max in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73096059-f8a64080-3eb1-11ea-9eab-f7f7c224ffdc.png)
Max expected:
![image](https://user-images.githubusercontent.com/57198117/73096011-d7ddeb00-3eb1-11ea-969b-4aae2e30a956.png)

XL in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73096094-0b207a00-3eb2-11ea-9de7-645b878eab8c.png)
XL expected:
![image](https://user-images.githubusercontent.com/57198117/73096110-1673a580-3eb2-11ea-80b7-808ef7528883.png)

Large in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73096140-28554880-3eb2-11ea-83bb-84902cbcc344.png)
Large expected:
![image](https://user-images.githubusercontent.com/57198117/73096155-31deb080-3eb2-11ea-8886-cc118d5eaa08.png)

Med in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73096268-68b4c680-3eb2-11ea-86b9-1ac70161f22d.png)
Med expected:
![image](https://user-images.githubusercontent.com/57198117/73096205-491d9e00-3eb2-11ea-97eb-90cb7d8fd0d7.png)

Small in Storybook:
![image](https://user-images.githubusercontent.com/57198117/73096322-7c602d00-3eb2-11ea-83a2-e335fd3742ae.png)
Small expected:
![image](https://user-images.githubusercontent.com/57198117/73096218-5044ac00-3eb2-11ea-8c58-766ba0455d70.png)

**Comment by andysherman2121** [comment] 2020-03-05 19:19
The tokens are being added correctly on our side, seems to be an issue with carbon. I opened an issue within Carbon's github. 

https://github.com/carbon-design-system/carbon/issues/5548

**Comment by andysherman2121** [comment] 2020-03-17 21:40
Carbon team solved this issue via this PR:
https://github.com/carbon-design-system/carbon/pull/5625
Waiting to close this issue once I can confirm it's working on our side

**Closed** 2020-06-22 12:56 UTC
Labels: Airtable Done, adopter support, adopter: drupal, bug, dev, severity 4
