### ISSUE TITLE
Pattern: LogoGrid - The card must be stretched to full screen size as per specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#2604] opened 2020-06-01 08:54 UTC
## Detailed description

Issue :- Card section is not stretched to end 2 end of the screen size. 

Expected :- Card must be stretched to full screen as per specs.

## Additional information

Actual :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5071f47c-cbe8-44c6-93d8-b89308e21473)

Expected :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/83a71594-6221-412d-a88b-b050a8a0d22a)

**Comment by RobertaJHahn** [comment] 2020-06-24 15:36
@kennylam It looks like this bug is a duplicate of (#2828).  Could you check whether this is the case and make any adjustments needed to close both this issue and (#2828).  I will close issue (#2828) as a dup.  Thanks.

**Closed** 2020-07-16 19:31 UTC
Labels: Airtable Done, QA, bug, severity 3
