### ISSUE TITLE
Pattern: Callout Media : Mismatch in pixel values  on desktop and mobile.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2402] opened 2020-05-15 09:51 UTC
Issue Description:- **1)** As per visual specs there should be 64px difference between media type and bottom of page on desktop and 64px difference between media type and bottom of page on mobile devices, where as in actual it more than 64px on desktop and more than 64px on mobile devices.

**2)** As per visual specs there should be 64px difference between top of the page and heading of pattern, but on desktop it is more than 64px.

**3)** As per visual specs there should be a 32px difference between media type and copy text, where as in mobile devices it is less than 32px.

## Steps to reproduce the issue

1. Enter url in the browser.
2. Select 'Callout with Media
3. Check the spacing difference between heading and top of page
4. Check the spacing difference between media type and bottom of page of page
5. Check the spacing difference between copy text and media type.

URL:- https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-blocks-calloutwithmedia--default

OS:- Windows10, Mac, iOS 12, 13, Android 8,9
Browsers:- Chrome, Safari, UC, Firefox![Bottom spacing in callout media.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/430154be-b1cf-4087-be28-f217a77cb80e)![bottom spacing in mobile callout media.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/8fc82831-8bf5-4d46-af97-b6110e0453b9)![CalloutMedia top of page and heading .jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/c340d4ae-f3ed-471a-a902-034c82f417e8)

**Comment by RobertaJHahn** [comment] 2020-05-15 19:58
Closing as this is a duplicate of issue #2395.

**Closed by RobertaJHahn** 2020-05-15 19:58 UTC
Labels: QA, bug, dev
