### ISSUE TITLE
Table of contents: issue with changing title

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#1386] opened 2020-02-12 16:22 UTC
## Table of contents: issue with changing title

-->

## Detailed description

> In Abstract it says "(when in tablet or mobile with top menu) Once the corresponding section starts passing behind pattern, the content of the Table of contents pattern changes to the title of it." Currently when a section passing the top menu in mobile/tablet the top menu title doesn't change. 

Wrong:
<img width="395" alt="Screen Shot 2020-02-12 at 10 08 20 AM" src="https://user-images.githubusercontent.com/56400049/74354775-76f35580-4d81-11ea-9971-0bf51dd9c7a4.png">

Correct:
<img width="371" alt="Screen Shot 2020-02-12 at 10 22 02 AM" src="https://user-images.githubusercontent.com/56400049/74354816-84a8db00-4d81-11ea-8a20-efc8d9d83fd4.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Table of contents

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The top menu in mobile/tablet should change title label based on which section is passed on the page. The top menu title is not changing based on section.

> What browser are you working in?
Firefox

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Web simplification

## Steps to reproduce the issue

1. Go to [table of contents](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--manually-define-menu-items)
2. View in full screen
3. Right click and click inspect 
4. View in mobile/tablet
5. Scroll on page 

## Additional information

- Screenshots or code
- Notes

**Comment by ljcarot** [comment] 2020-02-12 17:56
I think this was already reported as a bug by QA team.  Can you check by searching by bug, QA and Table of contents on our board?

**Comment by RobertaJHahn** [comment] 2020-02-12 18:08
@jacobottesen-dgc @ljcarot This is a duplicate of issue (#1369).  Closing.

**Closed by RobertaJHahn** 2020-02-12 18:08 UTC
Labels: bug, dev, package: patterns, web simplification
