### ISSUE TITLE
Storybook issue: Feature Card:- On opening in new tab error message is getting displayed.

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#2446] opened 2020-05-19 14:03 UTC
Issue Description:- When user enters new text in 'Card Heading' section and open feature card in new tab, story book is throwing "Unexpected end of JSON input" error message.

## Steps to reproduce the issue

1.Enter url in the browser.
2. Select 'Feature Card'
3. Clear existing text and enter new text in 'Card Heading'
4. Open feature card in new tab.

OS:- Windows 10, Mac, iOS 12, 13, Android 8,9
Browsers:- Chrome, Firefox, Safari, UC

URL:- https://ibmdotcom-react-staging.mybluemix.net/?path=/story/patterns-sub-patterns-featurecard--default![Feature card storybook issue.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/c1b7f142-4ffd-4d6b-a336-3e1e1b6b8192)

**Comment by ariellalgilmore** [comment] 2020-07-13 19:39
Hi @chetankan, @caiobozato and I both tried to reproduce the error on canary and it looks like it's working there. If this is okay, can we close this issue?

**Comment by greeshmareddyg** [comment] 2020-07-22 21:03
@chetankan @RobertaJHahn unable to reproduce this issue, It works fine.

**Comment by guilhermelMoraes** [comment] 2020-07-24 14:00
@chetankan tested against the canary and the staging versions, both working as expected. I think we can go ahead and close that one.

FYI @RobertaJHahn

**Closed** 2020-07-24 14:42 UTC
Labels: Airtable Done, QA, bug, severity 4
