### ISSUE TITLE
Update Locale Modal to use the ModalWrapper instead of ComposedModal

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#2124] opened 2020-04-20 14:35 UTC
#### User Story

> As a `[user role below]`:
IBM.com Library Developer

> I need to:
have LocaleModal uses the ModalWrapper instead of ComposedModal

> so that I can:
ensure the Carbon modal used is supported in the future

#### Acceptance criteria
 - [ ] LocaleModal using ModalWrapper instead of ComposedModal

**Comment by kennylam** [comment] 2020-05-19 15:16
duplicate of #2101

**Closed by kennylam** 2020-05-19 15:16 UTC
Labels: Airtable Done, dev, package: react, priority: medium
