### ISSUE TITLE
Blue border flicker in the Masthead during page load

### ISSUE THREAD

**Issue by sabhareesan** [carbon-design-system/ibm-dotcom-library#2382] opened 2020-05-14 09:43 UTC
During page load / reload there is a flicker in the L1 section border as shown in the below gif.

Adopter:  Profile
**If this requires a code fix.  It should be included the June release to support the Profile July Production deployment.**

## Detailed description
> Is this issue related to a specific component?
Masthead

> What browser are you working in?
It is only seen in Chrome browser, not in Firefox or Safari.

> What version of the IBM.com Library are you using?
"@carbon/ibmdotcom-react": "^1.6.0-rc.0",

> What offering/product do you work on? Any pressing ship or release dates we
ProfileUI

**Comment by sabhareesan** [comment] 2020-05-14 09:45
![c2223c00-95ee-11ea-8250-69ab208d2a2c](https://user-images.githubusercontent.com/23634668/81919690-c9991380-95f5-11ea-8bd4-5d1f4b122990.gif)

**Comment by JennySanchez** [comment] 2020-05-14 15:44
@RaphaelAmadeu Can you take a look of this for us?

**Comment by RaphaelAmadeu** [comment] 2020-05-15 13:58
@sabhareesan ,
I couldn't reproduce the issue, could you give us an url where it happens?
Thank you!

**Comment by sabhareesan** [comment] 2020-06-04 13:54
@RaphaelAmadeu , Sorry for the delay, this application is still under development. 
we have deployed it in our Dev Env today. I will DM you the URL.

**Comment by sabhareesan** [comment] 2020-06-18 04:08
Hi Team, Any update on this issue?

**Comment by RaphaelAmadeu** [comment] 2020-06-26 19:10
I talked with @sabhareesan and now I'm investigating what could be causing this issue, by building a repo that mirrors his implementation of our patterns.

**Comment by RaphaelAmadeu** [comment] 2020-07-02 13:47
I'm closing this issue, as we figured that the issue was not on our side.
Thank you!

**Closed by RaphaelAmadeu** 2020-07-02 13:47 UTC
Labels: Airtable Done, adopter support, bug, dev, severity 3

**Comment by sabhareesan** [comment] 2020-08-12 04:52
FYI
Blue border flicker occurs when the Masthead is rendered in the Server. As a workaround, we had made it to render in the Client Side(Browser) to avoid the flicker in our application. 

@RaphaelAmadeu @jeffchew But the application which does an SSR will see this issue.
