### ISSUE TITLE
image on ContentGroupSimple should be on ContentBlockSimple 

### ISSUE THREAD

**Issue by gregj0** [carbon-design-system/ibm-dotcom-library#1609] opened 2020-03-06 18:43 UTC
## Detailed description

> Describe in detail the issue you're having.
See above.  Reported first in slack in https://ibm-digitalcms.slack.com/archives/GMC4F575W/p1583502906035800

Note it looks like you may have started with https://github.com/carbon-design-system/ibm-dotcom-library/pull/1607

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
ContentGroupSimple and ContentBlockSimple

> What did you expect to happen? What happened instead? What would you like to
> see changed? 
Update to match Jill Stuart's spec.

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
1.5.0-nightly.2906

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Additional information

- Screenshots or code
- Notes

**Comment by ljcarot** [comment] 2020-03-09 14:47
Closing this issue, it has been resolved as not a bug and part of ingestion with component's prop with image.

**Closed by ljcarot** 2020-03-09 14:47 UTC
Labels: bug
