### ISSUE TITLE
[ToC] Blue bar on selected item should slide up and down the rail, not fading on and off

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/ibm-dotcom-library#2520] opened 2020-05-27 15:53 UTC
(Please note the light gray rail disappeared due to gif compression. Not a mistake.)

### Currently, the blue bar fades off and fades back on next to the new ToC item.

![May-27-2020 11-50-05](https://user-images.githubusercontent.com/15144993/83043075-6903d080-a010-11ea-9714-db447b9c1895.gif)

### Ideally, the blue bar is NOT a border of the ToC item, but an entity of its own. It slides up and down the rail smoothly, stopping at specific positions to highlight a ToC item. 

For better frame rate, see rendered video of the motion here: https://ibm.box.com/s/dwshp7411dwop4ipzmcya2i6u949hwq9

![May-27-2020 11-51-14](https://user-images.githubusercontent.com/15144993/83043070-673a0d00-a010-11ea-8cb8-10f105eba19e.gif)

Related: https://github.com/carbon-design-system/ibm-dotcom-library/issues/1742

**Comment by RobertaJHahn** [comment] 2020-05-28 21:27
This is a duplicate of issue (#2424).  Closing this issue.

**Closed by RobertaJHahn** 2020-05-28 21:27 UTC
Labels: bug, dup
