### ISSUE TITLE
[MM] Attempting to scroll through the mega menu and the home page scrolls instead

### ISSUE THREAD

**Issue by lily-kenney** [carbon-design-system/ibm-dotcom-library#3633] opened 2020-08-19 13:42 UTC
## Detailed description

> Describe in detail the issue you're having.

I click open one of the L0 labels and the corresponding mega menu opens. When I'm attempting to scroll down the mega menu on the trackpad on my Mac, the home page underneath scrolls instead. This is not expected as since the mega menu is in focus, I would expect the mega menu to be scrolling.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

The carbon mega menu on top of the carbon home page.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect that when the mega menu is in focus, I would be scrolling through the mega menu and not the page itself.

> What browser are you working in?

Mac, Safari Version 13.1.2 (15609.3.5.1.3)

> What version of the IBM.com Library are you using?

The one pulled onto this site: https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

The 8/31 launch date for the mega menu + US HP

## Steps to reproduce the issue

1. Go to https://wwwstage.ibm.com/thought-leadership/ryan-test/index.html
2. Click on one of the L0 labels, the mega menu will open
3. Use the track pad to scroll, the page underneath scrolls intead

## Additional information
See video at: https://ibm.box.com/s/3sb8veyu29tpf8en6dgmnyjrhw0f968e

**Comment by lily-kenney** [comment] 2020-08-20 19:54
@RobertaJHahn , @jeffchew , @ljcarot - FYI, Elliott identified this as a showstopper for launch. I think we can keep the severity the same but make sure it's pinned as a hot fix?

**Comment by RobertaJHahn** [comment] 2020-08-20 20:06
@lily-kenney The issue is assigned to the August release.  We should be good.

**Closed** 2020-08-24 12:56 UTC
Labels: Airtable Done, adopter support, adopter: reboot, bug, dev, package: react, severity 3
