### ISSUE TITLE
Web component: Dotcom shell - locale selector, Large blank space is shown to the user

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library#3901] opened 2020-09-10 13:40 UTC
## Detailed description

On iPad & iPhone- Safari & chrome

Issue: On opening Geo region selector, large white (blank) space is displayed to user, then user has to scroll up/ down to get to the region selector.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/0e0bbe26-36ca-4fea-affa-4a7c1c7c6842)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/95c7509d-bb34-4b18-9e12-e5cc83e712e0)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1a776918-7ed9-482f-b636-030b9095bc7f)

**Comment by kennylam** [comment] 2020-09-10 14:32
Tested on both iPad/iPhone (iOS13) and cannot reproduce either on page load or when scrolling.

![IMG_C96B7B7A5D7B-1](https://user-images.githubusercontent.com/909118/92745978-d41fab80-f350-11ea-9515-12f4eeb8d53b.jpeg)

![IMG_E0F14FD46F0B-1](https://user-images.githubusercontent.com/909118/92746005-d97cf600-f350-11ea-9372-07980ed3d2c6.jpeg)

**Comment by Praveen-sr** [comment] 2020-09-11 07:58
@kennylam This issue is with iOS 12 on iPhone and iPad.

**Comment by RobertaJHahn** [comment] 2020-09-11 20:29
Both Kenny and Andy tested on iOS devices and could not reproduce.  Closing.

**Closed by RobertaJHahn** 2020-09-11 20:29 UTC
Labels: Airtable Done, bug, dev, package: web components, severity 2
