### ISSUE TITLE
## Footer QA design: expressive-heading-02 wrong text

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#2377] opened 2020-05-13 19:21 UTC
## Footer QA design: expressive-heading-02 wrong text

-->

## The "Information for..." should be "Information for:" for the link title.

![Screen Shot 2020-05-13 at 2.16.59 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/3a179dfe-eb26-46bd-b688-36ad21edd058)

> Is this issue related to a specific component?
Footer

> What browser are you working in?
Google Chrome

## Steps to reproduce the issue

1. View footer in storybook http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-footer--default
2. View "Information for" link heading

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment] 2020-05-15 15:49
This information is being sourced by the same file as v18.  Tina Williams manages this file.  Working as intended.  Closing.

**Closed by RobertaJHahn** 2020-05-15 15:49 UTC
Labels: bug, dev
