### ISSUE TITLE
When JavaScript is disabled, the footer is gone on the carbon page (no links in the footer)

### ISSUE THREAD

**Issue by alainmachu** [carbon-design-system/ibm-dotcom-library#720] opened 2019-11-21 17:28 UTC
![Links in footer gone when JS disabled](https://user-images.githubusercontent.com/48733809/69361419-7358a280-0c5a-11ea-9238-254a63c5a0dc.jpg)

## Detailed description

1- see page 
https://ibm-com-search-beta.mybluemix.net/search?lang=us&cc=en&q=spss&nojs=true

**Note:** JavaScript is disabled

Look at the footer, all the links are gone, see screenshot attached

> Is this a feature request (new component, new icon), a bug, or a general
> issue? Bug

> What did you expect to happen? What happened instead? What would you like to
> see changed? The footer should be working even when JavaScript is disabled

> What browser are you working in? Chrome

- Screenshots or code
- Notes

**Comment by jeffchew** [comment] 2019-11-21 19:42
@alainmachu as mentioned in slack, there is a different way of rendering the footer from the server side, you can see instructions here:
https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/packages/react/src/components/Footer#server-side-rendering

**Comment by ljcarot** [comment] 2019-11-22 19:27
Working as intended.  Closing issue since the behavior of loading nav data on client side is different from SSR and as such footer will not display content if js is disabled.  As suggested above, use the ssr approach for your implementation.

**Closed by ljcarot** 2019-11-22 19:27 UTC
Labels: bug, question
