### ISSUE TITLE
Pattern:- Table of Content:- In landscape mode title are not getting displayed in bold(iOS).

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1644] opened 2020-03-10 14:05 UTC
Issue:- On iOS mobile phone in landscape mode 'Table of Content' titles are not getting displayed in bold.

## Steps to reproduce the issue

1. Enter the url in thebrowser
2. Click on 'Table of Contents'
3. Turn mobile in landscape mode.

## Additional information

OS:- iOS 12, 13
Device :- iPhone 11 pro, 11, Xs, Xs max, X, 8![Table of contents in landscape mode.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/0c14bc2d-4d99-46e4-9747-91a889e8160a)
Browser:- Chrome, Safari

**Comment by jeffchew** [comment] 2020-03-20 14:05
Moving this out to sprint 7.

**Comment by RaphaelAmadeu** [comment] 2020-03-30 15:54
This is caused by IOS and how it handles the font-sizes on landscape, as this is a low priority and none of the found solutions are suitable, we are putting this on hold.

**Comment by jeffchew** [comment] 2020-04-13 19:20
@RobertaJHahn I don't think this is a `Sprint Must Have`, right? I think we should push this out.

cc: @ljcarot @RaphaelAmadeu

**Comment by ljcarot** [comment] 2020-04-14 13:25
I agree we can push this out if sev 4.

**Comment by jeffchew** [comment] 2020-04-14 13:32
@RobertaJHahn moving this out to the next sprint.

**Comment by diegomarcuz** [comment] 2020-08-12 14:21
Hey @chetankan, I was checking it and seems to be bold, could you check again ?

This screenshot is from Iphone 11 Pro IOS 13

![Screen Shot 2020-08-12 at 11.18.03.png](https://images.zenhubusercontent.com/5eed25994ac8fb057241e3b2/3cfb29f4-f00c-464c-b644-a192de1a5161)

**Comment by diegomarcuz** [comment] 2020-08-18 13:44
@chetankan checking again...

**Comment by diegomarcuz** [comment] 2020-08-18 20:45
Hey @chetankan, could you check again ?? PR: [#3614](https://app.zenhub.com/workspace/o/carbon-design-system/ibm-dotcom-library/issues/3614)

**Closed** 2020-08-25 11:59 UTC
Labels: Airtable Done, bug, dev, package: react, severity 4
